[package]
name = "runtime"
version = "0.0.1"
authors = ["Markus Ineichen <kusi.ineichen@gmail.com>"]
edition = "2018"

[dependencies]
ioc-rs = { path = "../../" }
interface = { path = "../interface" } 
libloading = "0.6"
